@OTelErrorDiagnosticsDemo.Api_HostAddress = http://localhost:5173

POST {{OTelErrorDiagnosticsDemo.Api_HostAddress}}/message
Accept: application/json
Content-Type: application/json
traceparent: null

{
  "data": "ABC"
}

###
